name: sync

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 2 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: rclone sync
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONF }}' > ~/.config/rclone/rclone.conf
          rclone sync ${{ secrets.ONEDRIVE_ORIGIN }} ${{ secrets.ONEDRIVE_BACKUP1 }}

      - uses: gautamkrishnar/keepalive-workflow@1.0.7
