name: sync

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 2 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: curl https://rclone.org/install.sh | sudo bash

      - name: rclone sync
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONF }}' > ~/.config/rclone/rclone.conf
          rclone sync ${{ secrets.ONEDRIVE_ORIGIN }}: ${{ secrets.ONEDRIVE_BACKUP1 }}:
          rclone sync ${{ secrets.ONEDRIVE_ORIGIN }}: ${{ secrets.ONEDRIVE_BACKUP2 }}:${{ secrets.ONEDRIVE_ORIGIN }}
          rclone sync ${{ secrets.ONEDRIVE_ORIGIN_PERSONAL }}: ${{ secrets.ONEDRIVE_BACKUP2 }}:${{ secrets.ONEDRIVE_ORIGIN_PERSONAL }}

      - uses: actions/checkout@v3

      - uses: gautamkrishnar/keepalive-workflow@master

