name: sync

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 2 * * *

concurrency:
  group: environment

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Rclone sync
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONF }}' > ~/.config/rclone/rclone.conf
          rclone sync --onedrive-delta --fast-list --drive-chunk-size 128M ${{ secrets.ONEDRIVE_ORIGIN }}: ${{ secrets.ONEDRIVE_BACKUP1 }}:${{ secrets.ONEDRIVE_ORIGIN }}
          rclone sync --onedrive-delta --fast-list --drive-chunk-size 128M --exclude='/Personal Vault/**' ${{ secrets.ONEDRIVE_ORIGIN_PERSONAL }}: ${{ secrets.ONEDRIVE_BACKUP1 }}:${{ secrets.ONEDRIVE_ORIGIN_PERSONAL }}
        env:
          RCLONE_USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0'
          RCLONE_CHECKERS: 16
          RCLONE_BUFFER_SIZE: 4G
          RCLONE_CHECK_FIRST: 1

      - name: Update rclone configuration
        run: gh secret set RCLONE_CONF --repo '${{ github.repository }}' < ~/.config/rclone/rclone.conf
        env:
          GH_TOKEN: ${{ secrets.ACTION_SECRET_TOKEN }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
