name: sync

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 2 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          DEBIAN_FRONTEND=noninteractive apt update
          DEBIAN_FRONTEND=noninteractive apt install rclone

      - name: rclone sync
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          rclone sync ${{ secrets.ONEDRIVE_ORIGIN }} ${{ secrets.ONEDRIVE_BACKUP1 }}
